-- Run this in Supabase SQL Editor for the project used by Easekolar.
-- It creates the table required by admin-scholarships Programs tab.

create table if not exists public.campus_programs (
  id bigint generated by default as identity primary key,
  campus text not null,
  department text not null,
  course_name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campus_programs_unique unique (campus, department, course_name)
);

create index if not exists campus_programs_campus_idx
  on public.campus_programs (campus);

create index if not exists campus_programs_department_idx
  on public.campus_programs (department);

create or replace function public.set_campus_programs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_campus_programs_updated_at on public.campus_programs;
create trigger trg_campus_programs_updated_at
before update on public.campus_programs
for each row
execute function public.set_campus_programs_updated_at();

-- Keep API access simple for this project style (client-side writes via anon key).
alter table public.campus_programs disable row level security;

grant select, insert, update, delete
on table public.campus_programs
to anon, authenticated;

grant usage, select
on sequence public.campus_programs_id_seq
to anon, authenticated;

